---
title: "Homework Assignment #4"
subtitle: "Prioritizing potential aquaculture"
author: "Kaiju Morquecho"
date: last-modified
execute: 
  eval: true
  warning: false
  message: false
format:
  html:
    toc: true
editor_options: 
  chunk_output_type: console
---
##### Load data and libraries

```{r}
library(stars)
library(tidyverse)
library(tmap)
library(sf)
library(here)
library(raster)
library(terra)
library(FNN)
```

```{r}
sst_2008 <- read_stars(here("data","average_annual_sst_2008.tif"))
sst_2009 <- read_stars(here("data","average_annual_sst_2009.tif"))
sst_2010 <- read_stars(here("data","average_annual_sst_2010.tif"))
sst_2011 <- read_stars(here("data","average_annual_sst_2011.tif"))
sst_2012 <- read_stars(here("data","average_annual_sst_2012.tif"))
depth <- read_stars(here("data","depth.tif"))
eez <- read_sf(here("data","wc_regions_clean.shp"), quiet = TRUE)

```

##### Process data

```{r}
# Check that CRS match
st_crs(sst_2008) == st_crs(sst_2009)
st_crs(sst_2008) == st_crs(sst_2010)
st_crs(sst_2008) == st_crs(sst_2011)
st_crs(sst_2008) == st_crs(sst_2012)

sst_stack <- c(sst_2008, sst_2009, sst_2010, sst_2011, sst_2012)

sst_stack <- st_redimension(sst_stack) # mean function was applied to layers separately until i used st_redimension

mean_sst <- st_apply(sst_stack, c(1,2), mean, na.rm = TRUE) # mean sst accross 2008-2012

mean_sst <- mean_sst - 273.15 # convert average sst from kelvin to celsius
```

```{r fig.height= 8 , fig.width= 10}
map1 <- tm_shape(mean_sst) +
  tm_raster(palette = rev(hcl.colors(5,"Inferno")),
            style = "cont",
            colorNA = "black",
            textNA = "Land",
            title = "Sea surface temp (째C)",
            ) +
  tm_graticules(lwd = 0.3, 
                col = "white") +
  tm_layout(fontfamily = "courier",
            main.title = "Sea surface temperature, U.S West Coast",
            main.title.size = 1,
            inner.margins = c(0.001, 0.001, 0.001, 0.001),
            legend.position = c("left","BOTTOM"),
            legend.text.size = 0.5,
            legend.title.color = "black",
            legend.text.color = "black",
            legend.height = 5,
            legend.title.size = 0.5)

map1
```

```{r}
# check that depth matches mean_sst crs and transform if not
if(st_crs(mean_sst) == st_crs(depth)) {
  print("crs match!")
} else { 
  depth <- st_transform(depth, st_crs(mean_sst))
}
```

```{r}
# double-check after transformation 
if(st_crs(mean_sst) == st_crs(depth)) {
  print("crs match!")
} else { 
  print("crs don't match!")
}
```

```{r}
# match extents and resample to mean_sst resolution using nearest neighbor ("near")
depth_resampled <- st_warp(depth,mean_sst, method = "near")
# stack to verify
depth_sst <- c(depth_resampled,mean_sst)
# stacked successfully 
```

```{r}
map2 <- tm_shape(depth_resampled) +
  tm_raster(palette = hcl.colors(8,"Berlin"),
            style = "cont",
            title = "Depth (m)") +
  tm_graticules(lwd = 0.3,
                col = "white") +
  tm_layout(fontfamily = "courier",
            main.title = "Depth, U.S West Coast",
            main.title.size = 1,
            inner.margins = c(0.001, 0.001, 0.001, 0.001),
            legend.position = c("left","BOTTOM"),
            legend.text.size = 0.5,
            legend.title.color = "white",
            legend.text.color = "white",
            legend.height = 5,
            legend.title.size = 0.5)

map2
```

##### Find suitable locations for oysters

```{r fig.height= 8 , fig.width= 10}

# reclassify mean_sst
rcl_sst <- matrix(c(-Inf, 11, NA,
                11, 30, 1,
                30, Inf, NA),
                ncol = 3, byrow = TRUE)

mean_sst <- rast(mean_sst)

reclassified_sst <- classify(mean_sst, rcl = rcl_sst)

# reclassify depth

rcl_depth <- matrix(c(-Inf, -70, NA,
                -70, 0, 1,
                0, Inf, NA),
                ncol = 3, byrow = TRUE)

depth_resampled <- rast(depth_resampled)

reclassified_depth <- classify(depth_resampled, rcl = rcl_depth)

suitable_locations <- reclassified_sst * reclassified_depth
```


```{r fig.height= 8 , fig.width= 10}
map3 <- tm_shape(reclassified_sst) +
  tm_raster(palette = "lightgoldenrod",
            style = "cat",
            colorNA = "black",
            title = "Sea surface temp (째C)",
            labels = "Suitable location",
            textNA = " ") + 
  tm_graticules(lwd = 0.3, 
                col = "white") +
  tm_layout(fontfamily = "courier",
            fontface = "bold",
            main.title = "Suitable SST (째C) for oyster growth, U.S West Coast",
            main.title.size = 0.7,
            inner.margins = c(0.001, 0.001, 0.001, 0.001),
            legend.position = c(0.57,0.8),
            legend.frame = FALSE,
            legend.text.size = 0.4,
            legend.title.size = 0.6,
            legend.title.color = "white",
            legend.text.color = "white",
            legend.text.fontface = "bold",
            legend.title.fontface = "bold")
map3
```

```{r}
map4 <- tm_shape(reclassified_depth) +
  tm_raster(palette = "seagreen2",
            style = "cat",
            colorNA = "black",
            title = "Suitability",
            labels = "Suitable location",
            textNA = " ") +
  tm_graticules(lwd = 0.3, 
                col = "white") +
  tm_layout(fontfamily = "courier",
            main.title = "Suitable depth(m) for oyster growth, U.S West Coast",
            main.title.size = 0.7,
            inner.margins = c(0.001, 0.001, 0.001, 0.001),
            legend.position = c(0.57,0.8),
            legend.frame = FALSE,
            legend.text.size = 0.4,
            legend.title.size = 0.6,
            legend.title.color = "white",
            legend.text.color = "white",
            legend.text.fontface = "bold",
            legend.title.fontface = "bold")

map4
```

```{r}
map5 <- tm_shape(suitable_locations) +
  tm_raster(palette = "seagreen2",
            style = "cat",
            colorNA = "black",
            title = "Suitability",
            labels = "Suitable location",
            textNA = " ") +
  tm_graticules(lwd = 0.3, 
                col = "white") +
  tm_layout(fontfamily = "courier",
            main.title = "Suitable oyster growth locations (m)(째C)",
            main.title.size = 0.7,
            inner.margins = c(0.001, 0.001, 0.001, 0.001),
            legend.position = c(0.57,0.8),
            legend.frame = FALSE,
            legend.text.size = 0.4,
            legend.title.size = 0.6,
            legend.title.color = "white",
            legend.text.color = "white",
            legend.text.fontface = "bold",
            legend.title.fontface = "bold")

map5
```

```{r}
eez_map <- tm_shape(eez) +
  tm_polygons(col = "rgn",
              palette = hcl.colors(5, "Temp"),
              border.col = "black",
              lwd = 0.7,
              title = "EEZ region") +
  tm_text(text = "rgn",
          size = 0.6,
          col = "black",
          fontface = "bold") +
  tm_layout(fontfamily = "courier",
            main.title = "Exclusive Economic Zone (EEZ)",
            main.title.size = 0.8,
            main.title.fontface = "bold",
            legend.text.size = 0.5,
            legend.title.size = 0.6,
            legend.position = c("left","BOTTOM"),
            bg.color = "skyblue") +
  tm_graticules(col = "black",
                lwd = 0.3,
                alpha = 0.5) 
  
eez_map
```

```{r}
# check crs of eez and 
if(st_crs(suitable_locations) == st_crs(eez)) {
  print("crs match!")
} else { 
  print("crs don't match!")
}

eez <- st_transform(eez, st_crs(suitable_locations))

if(st_crs(suitable_locations) == st_crs(eez)) {
  print("crs match!")
} else { 
  print("crs don't match!")
}
```

```{r}
# make mask of suitable locations
mask_locations <- mask(suitable_locations, eez)

# find grid cells area 
cell_area <-cellSize(x = mask_locations,
             mask = TRUE,
             unit = "km")

# rasterize eez vector
eez_raster <- rasterize(eez,cell_area,
                        field = "rgn_id") 

# use zonal function to find suitable areas within each eez
suitable_eez <- zonal(x = cell_area,
                      z = eez_raster, 
                      fun = "sum",
                      as.raster = TRUE,
                      na.rm = TRUE)

species_map <- tm_shape(depth_resampled) +
  tm_raster(palette = hcl.colors(8,"Berlin"),
            style = "cont",
            legend.show = FALSE) +
  tm_shape(suitable_eez) +
  tm_raster(palette = rev(hcl.colors(5, "BuGn")),
            style = "cat",
            title = expression("Zone priority / total suitable area (km^2*)"),
            labels = c("Lowest, 438",
                       "1,533",
                       "3,225",
                       "4,097",
                       "Highest, 4,923"),
            legend.is.portrait = FALSE) +
  tm_shape(eez) + 
  tm_text(text = "rgn",
          size = 0.55,
          col = "black") +
  tm_layout(fontfamily = "courier",
            fontface = "bold",
            main.title = "Total Suitable Area for Oyster Growth Across EEZs",
            main.title.size = 0.8,
            main.title.fontface = "bold",
            inner.margins = c(0.001, 0.001, 0.001, 0.001),
            legend.text.size = 0.6,
            legend.title.size = 0.6,
            legend.title.color = "Black",
            legend.text.color = "Black",
            legend.outside = TRUE,
            legend.outside.position = "bottom",
            legend.stack = "horizontal",
            legend.width = 7, 
            legend.height = 0.5) +
  tm_graticules(col = "white",
                lwd = 0.3,
                alpha = 0.5) 

species_map 

```

